### ISSUE TITLE
Proposal creation: Remove proposal drafts

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/pgt-web-app#11]
**User Story:**
As a community member,
I want to create proposals easily 
so that I can participate in the governance process without needing to leave the platform

**Acceptance Criteria:** 
- Given that the user wants to remove a proposal draft,
- When the user clicks on My proposal section,
- [x] Then the user will be able to remove his draft by using the trash can Icon

Provisional UI:  https://app.visily.ai/projects/4a98eee4-af36-416a-8432-88b586730009/boards/1351944/elements/622268529

**Comment by criptowaco** [comment]
Given that I want to remove a proposal draft,
When I click on My proposal section,
Then I am able to remove my draft by using the trash can Icon

![image](https://github.com/user-attachments/assets/bdfe3b82-ca3b-4e0f-b660-37330ed6a902)

**Comment by CristinaEche** [comment]
@iluxonchik 

Works as expected

https://github.com/user-attachments/assets/b0d8838d-e0ac-4ca7-97fc-c9a30e685810

https://github.com/user-attachments/assets/9994b149-12a9-46fe-8b9d-adff3fefaf15
