### ISSUE TITLE
Admin section: Landing into the admin section

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/pgt-web-app#13]
**User story**
As a system administrator
I want to manage all the funding round activities, such as reviewer groups, funding round phases, 
So that I can set up each funding round properly

**Acceptance Criteria**
- Given an admin section icon in the navigation bar
- When I click on the icon
- Then the admin dashboard with all the manage options will be displayed: 
- [x] Manage reviewers
- [x] Manage discussion topics
- [x] Manage funding rounds
- [x] Manage proposal status
- [x] Count votes

Provisional UI: https://app.visily.ai/projects/4a98eee4-af36-416a-8432-88b586730009/boards/1351944/elements/616759820

**Comment by CristinaEche** [comment]
I Have the icon, and i can land in the section as expected:

https://github.com/user-attachments/assets/07d784eb-0613-4258-9908-d84b5fd8febf

**Comment by remigiusz-antczak** [comment]
I don't see the admin section in the navigation bar (as a cog) after logging in:
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/daea8613-caa7-42bb-9f85-401d94f3fdbe">

But, when I go manually to pgt-staging.minaprotocol.network/admin, it works correctly:
<img width="1528" alt="image" src="https://github.com/user-attachments/assets/01e6b09e-8cb5-4dcd-a7ca-847c7829032d">

After accessing the admin section manually via a URL, I can see it afterward in the navigation bar. I also noticed refreshing the website after logging in solves this; also everything else seems to work correctly:

https://github.com/user-attachments/assets/6cacbb76-4908-4350-8fa3-7cf7700db183

**Comment by CristinaEche** [comment]
Waiting for the fix, no big Issue. you can see it when the page is refreshed.
