### ISSUE TITLE
Proposal submission to a Funding Round 

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/pgt-web-app#25]
**User Story**
As a Community member,
I want to submit a proposal for a funding round,
So that it can be considered for funding.

**Acceptance criteria:** 
**Submit a proposal:**

- Given that the user wants to submit a proposal he can do it from the home page proposals list or my proposals section,
- When the user clicks on submit proposal,
- [x]  Then the proposal is submitted to the funding round and it cannot be edited.
- [x] A Notification of submission deadlines should be provided to all community members.

Provisional UI: https://app.visily.ai/projects/4a98eee4-af36-416a-8432-88b586730009/boards/1351944/elements/628258685

**Comment by criptowaco** [comment]
Given I am a user in the "My Proposals" section,
When I click "Submit Proposal",
Then I must select a Funding Round and click "Continue",
Then a message appears stating the proposal cannot be edited once submitted. I must click to agree to the GDPR terms, or the "Submit Proposal" button remains disabled. I can view the GDPR terms by clicking on them.
Finally, when I click "Submit Proposal", I see a confirmation that my proposal has been submitted to the specified Funding Round in the "My Proposals" section.

![Captura de pantalla 2024-11-29 a las 12 01 24](https://github.com/user-attachments/assets/4f05dfa9-4160-4e64-abeb-cc12b53886cd)
![Captura de pantalla 2024-11-29 a las 12 02 02](https://github.com/user-attachments/assets/3c2baca6-d874-4a52-8a0b-2380d9429deb)
![Captura de pantalla 2024-11-29 a las 12 02 18](https://github.com/user-attachments/assets/24297597-445f-4095-83ab-588279e84b55)
![Captura de pantalla 2024-11-29 a las 12 02 31](https://github.com/user-attachments/assets/b33ada07-0866-40a1-a178-0ede6a46a3e2)
![Captura de pantalla 2024-11-29 a las 12 02 52](https://github.com/user-attachments/assets/9bb69dd2-54f4-4bc8-a804-18918a41530f)

**Comment by remigiusz-antczak** [comment]
I was able to successfully submit a proposal, too:

<img width="1171" alt="image" src="https://github.com/user-attachments/assets/60883e4f-a1ec-4516-832f-963c62ed9a46">
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/cfadf08a-b6eb-4716-b998-aaf81e323488">
<img width="1237" alt="image" src="https://github.com/user-attachments/assets/27eef17d-8dd3-4f95-8e9b-bd4801b5e245">

**Comment by CristinaEche** [comment]
@iluxonchik 

Successfully submitted the proposal, however the submission button can be changed to a brighter color , since in light gray seems dimmed. (this could be solved with the color palette application)

![Image](https://github.com/user-attachments/assets/0b531d18-eb32-4bea-841c-5beae2851a30)


![Image](https://github.com/user-attachments/assets/3c74365f-bf04-4328-bea5-209afd91f424)


![Image](https://github.com/user-attachments/assets/4e6d277f-a62e-4204-b36c-fbe41f0e8d47)


![Image](https://github.com/user-attachments/assets/ff66ec19-fc69-4345-add5-c7619d119ceb)

![Image](https://github.com/user-attachments/assets/66d41ee6-ff2f-4790-bf48-8ed6f4b89a6d)

![Image](https://github.com/user-attachments/assets/660bfddb-1994-4673-825d-b04a91150ab5)

**Comment by CristinaEche** [comment]
Updated Home:

![Image](https://github.com/user-attachments/assets/fb0dc971-a74e-44b3-b201-b935edefa182)
