### ISSUE TITLE
Proposal Consideration - Reviewer flow

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/pgt-web-app#28]
**User Story**
As a Reviewer 
I want  to provide reasoning for the consideration of a proposal in the active funding round
So that the proposal can move to the deliberation phase

**Acceptance Criteria**

- Given that the user is in the proposal consideration phase,
- When they scroll to the proposals list,
- Then they should see a list of proposals to consider:
- [x] Provide reviewer flow/options
- [x] Add reviewer reasoning into the proposal profile
- Proposals not moving to the next phase should be removed from the active proposals list

Provisional UI: https://app.visily.ai/projects/4a98eee4-af36-416a-8432-88b586730009/boards/1351944/elements/616679360

**Comment by remigiusz-antczak** [comment]
I can see the lists of proposals to consider:
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/8db9abbe-2685-40a3-bcb7-06adbd6994e3">

I can also add reviewer reasoning to the proposal profile: 
<img width="1558" alt="image" src="https://github.com/user-attachments/assets/9bff8226-3558-4666-9e78-ebd71aafdcda">

The header is also updating correctly based on completed reviews:
<img width="995" alt="image" src="https://github.com/user-attachments/assets/3893e545-3450-4660-958c-e9787d4a80c7">

And I can also see the proposals I reviewed with my decision, and I'm able to edit it 
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/e98cb6ef-f45a-42f1-a3a5-55b2d1845843">
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/2a9a90ae-a49c-44af-97e4-08529e93a6a0">

**Comment by CristinaEche** [comment]
See lees - see more it's going to be like in the UI instead of going to another page to see proposal details
