### ISSUE TITLE
Discord login: Access the platform with the Discord handle 

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/pgt-web-app#4]
**User Story**
As a user, 
I want to log in to the platform using my Discord handle 
So that I can access the platform without creating a separate account

**Acceptance criteria:**

- Given that the user is on the Discord channel,
- When they click the "Login to MEF" button,
- [x] Then user should be redirected to the MEF website

Notes: 
A token will be created in the DB, indicating the user has logged in.
Provisional channel/entry point: https://discord.com/channels/1229012241710448640/1267780879900606516

**Comment by remigiusz-antczak** [comment]
I successfully logged in to the MEF website using the "Login to MEF" button on Discord:
* <img width="706" alt="image" src="https://github.com/user-attachments/assets/ed7a4270-3f9a-4235-bf4c-d18c65d86c78">
* <img width="745" alt="image" src="https://github.com/user-attachments/assets/4c80972e-7555-4468-be6f-2fd77787bca0">
* <img width="1577" alt="image" src="https://github.com/user-attachments/assets/b1fcfe84-a6f4-4708-8193-443a0e7e017f">


I have two questions to consider maybe for the following improvements: 
1. **Can we enable users to log in directly via the MEF website?** To lower the number of steps and platforms, but not critical for the existing scope.
2. **Could we verify if the logging-in user is a member of the Mina Discord server (or even has a specific role)?** To double-check if it's not a random bot account. We could also require people to have a specific role on Discord before participating in MEF, such as being on the Mina server for at least 6 months and having a role indicating that a user understands and knows how to participate in MEF. These are just some open ideas to discuss further and are not critical for the existing scope.

**Comment by remigiusz-antczak** [comment]
Also, requiring users to log in every 15mins might be too much. Can we please extend this to maybe one day? 
<img width="653" alt="image" src="https://github.com/user-attachments/assets/ae67826e-0bcf-4cb8-987e-8e92862035c5">


Also, after positive log in, user needs to refresh the website to see their username in the top right corner. Is it something we could also fix to avoid confusing people?

**Comment by criptowaco** [comment]
As a Discord user, I am on the Discord channel called “consider”
When I click on the “Login to MEF” button,
Then I am redirected to the MEF website.

![image](https://github.com/user-attachments/assets/93538122-0c60-4ce8-84cf-defbc10d5200)
![image](https://github.com/user-attachments/assets/212dcda0-a690-4dfd-a50a-8a5582a0c6aa)

**Comment by CristinaEche** [comment]
> **User Story** As a user, I want to log in to the platform using my Discord handle So that I can access the platform without creating a separate account
> 
> **Acceptance criteria:**
> 
> * Given that the user is on the Discord channel,
> * When they click the "Login to MEF" button,
> * [x]  Then user should be redirected to the MEF website
> 
> Notes: A token will be created in the DB, indicating the user has logged in. Provisional channel/entry point: https://discord.com/channels/1229012241710448640/1267780879900606516

- I can log in to the website, and now I do not have to refresh the page, the issue is solved
- I have waited a few minutes and do not have to log in again from Discord.

https://github.com/user-attachments/assets/c094b690-ca23-45d9-83b9-9a9e199c7d9f



CC: @iluxonchik @remigiusz-antczak @criptowaco

**Comment by CristinaEche** [comment]
> I successfully logged in to the MEF website using the "Login to MEF" button on Discord:
> 
> * <img alt="image" width="706" src="https://private-user-images.githubusercontent.com/140408771/388456615-ed7a4270-3f9a-4235-bf4c-d18c65d86c78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTE3NzIsIm5iZiI6MTczMjcxMTQ3MiwicGF0aCI6Ii8xNDA0MDg3NzEvMzg4NDU2NjE1LWVkN2E0MjcwLTNmOWEtNDIzNS1iZjRjLWQxOGM2NWQ4NmM3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QxMjQ0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWI1ZDQ0ZTMxM2QwM2ZlNDE1MWZkZDc4MjQ0OWE4OWQ2NGVjOGRiYTQwZDAyOTM3N2QyMTIxMGQ1NmJjYmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R4-hZ4zclmIGlixe9irRnw1CUrX_rr2CKG1VA3mZKL8">
> * <img alt="image" width="745" src="https://private-user-images.githubusercontent.com/140408771/388453861-4c80972e-7555-4468-be6f-2fd77787bca0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTE3NzIsIm5iZiI6MTczMjcxMTQ3MiwicGF0aCI6Ii8xNDA0MDg3NzEvMzg4NDUzODYxLTRjODA5NzJlLTc1NTUtNDQ2OC1iZTZmLTJmZDc3Nzg3YmNhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QxMjQ0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzAwNTg1NDBkZTc4MTUyNjRkOTI4OTEyOGE1NTE2ZGY4MDUwMjU4ZjM0OWJmODMzMjMxMzBiNjIxY2IwMDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fdDp77RpmtWVZPp4_hrkOjJvjZvmHJi3jFVP8M-Mjag">
> * <img alt="image" width="1577" src="https://private-user-images.githubusercontent.com/140408771/388454101-b1fcfe84-a6f4-4708-8193-443a0e7e017f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTE3NzIsIm5iZiI6MTczMjcxMTQ3MiwicGF0aCI6Ii8xNDA0MDg3NzEvMzg4NDU0MTAxLWIxZmNmZTg0LWE2ZjQtNDcwOC04MTkzLTQ0M2EwZTdlMDE3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QxMjQ0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzJjZmJlNDA4Zjc4MTk4YmZiMWUxNzYzOWZjYmIwMDYwMTY5NzAwYTYwNDRiNzVmMTQ0NjMyZjkwNTI5NDk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.15q18Rlxgi9Z3fI5-TjsStkOSiLVQoCgy_oFLXN6wVI">
> 
> I have two questions to consider maybe for the following improvements:
> 
> 1. **Can we enable users to log in directly via the MEF website?** To lower the number of steps and platforms, but not critical for the existing scope.
> 2. **Could we verify if the logging-in user is a member of the Mina Discord server (or even has a specific role)?** To double-check if it's not a random bot account. We could also require people to have a specific role on Discord before participating in MEF, such as being on the Mina server for at least 6 months and having a role indicating that a user understands and knows how to participate in MEF. These are just some open ideas to discuss further and are not critical for the existing scope.

___________

Yes @remigiusz-antczak we can consider this for improvements for the following iterations since we are testing on the GovBot_dev and we do not have roles. and for this trial, we are using a opt-in form.

**Comment by CristinaEche** [comment]
@iluxonchik 
The login channel must be updated to the forum one: 

https://discord.com/channels/1229012241710448640/1301096522452303894

**Comment by iluxonchik** [comment]
Hello, on this now!

**Comment by iluxonchik** [comment]
Merged https://github.com/MinaFoundation/PGT_govbot/pull/55

**Comment by CristinaEche** [comment]
- [ ] If more than 30 secs. Login error
- [ ] if login immediately successful login

https://github.com/user-attachments/assets/97082920-abcb-40d8-a018-4e5ad4688b72
