### ISSUE TITLE
Proposal consideration - Community member vote: Add env variable to point OCV server

### ISSUE THREAD

**Issue by leomanza** [MinaFoundation/pgt-web-app#64]
proposed name: NEXT_PUBLIC_OCV_API_BASE_URL
value: http://on-chain-voting-server:8080

**Comment by leomanza** [comment]
After the env variable is added on the web project, reach out @simisimis to add the env variable for deployment

**Comment by iluxonchik** [comment]
Hi, all done on my side. I don't think there's anything to test for @CristinaEche. I'd propose we close this. Or we can await for resolution from @simisimis

**Comment by CristinaEche** [comment]
@iluxonchik @leomanza already done by @simisimis .

https://discord.com/channels/484437221055922177/1255580750946762832/1315973051996966952

Please let us know once finally implemented.

CC: @remigiusz-antczak
