### ISSUE TITLE
Proposal Creation 

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/pgt-web-app#8]
**User Story:**
As a community member,
I want to create proposals easily 
so that I can participate in the governance process without needing to leave the platform

**Acceptance criteria:**

- Given that the user wants to create a proposal he can do it from the home page or from the My proposals section,
- When the user clicks on create proposal,
- Then a proposal form will have to be filled

**Proposal Form:**
- A form template is available for proposal submissions.
- The form is accessible via a simple button within the Interface.
- The form includes fields for all required information for proposal submission, such as:
- [x] Proposal title
- [x] Abstract
- [x] Motivation 
- [x] Rationale
- [x] Delivery requirements
- [x] Security and Performance Considerations
- [x] Budget request
- [x] Discord handle (if not logged in with Discord)
- [x] Email 
- [x] The form guides users through the process, ensuring all necessary information is submitted.
- [x] Once created a list of proposals will be presented 

**Proposal validation and Error Handling:**

- [x] The form includes validation for required fields (e.g., users cannot submit an empty title or description).
- [x] Users receive clear error messages if required fields are missing or incorrectly filled.
- [x] Proposals cannot be submitted until all required fields are correctly completed.
- [x] Once a proposal is successfully created, users receive an immediate confirmation message.

Provisional UI: 
Entry points: from create a proposals or My proposals list: https://app.visily.ai/projects/4a98eee4-af36-416a-8432-88b586730009/boards/1351944/elements/628258532
Form: https://app.visily.ai/projects/4a98eee4-af36-416a-8432-88b586730009/boards/1351944/elements/629059923

**Comment by remigiusz-antczak** [comment]
I successfully created a new proposal and can see it on the list of proposals correctly, but it looks like error handling is yet to be implemented (the below image shows a notification after trying to save an empty draft - clicking on "Save Draft" button without completing all the required fields in the form):
<img width="1622" alt="image" src="https://github.com/user-attachments/assets/d430f39b-0260-4ce9-989d-b02aa8446f01">

**Comment by criptowaco** [comment]
As a user, I am at the home page and want to create a proposal 
When I click on create proposal,
Then a proposal form has to be filled

![image](https://github.com/user-attachments/assets/6dddb6dd-1a02-46ff-897c-647cdec7d7dd)
![image](https://github.com/user-attachments/assets/ba8e539c-995c-4d62-a8aa-43d5543efbfe)

**Comment by CristinaEche** [comment]
Error messages in the fields work as expected.

https://github.com/user-attachments/assets/8956e831-1442-4291-8594-627f491d17c0

**Comment by CristinaEche** [comment]
@iluxonchik - The discord handle should be auto-filled when login via Discord 

![Image](https://github.com/user-attachments/assets/a17f0688-0d70-41ba-92e9-a8809ed1b9b9)

**Comment by CristinaEche** [comment]
@iluxonchik The proposal creation confirmation should be more visible

![Image](https://github.com/user-attachments/assets/a6a782da-0962-44c2-b5db-6c2cc3a1bdf6)

**Comment by CristinaEche** [comment]
**Complete proposal creation evidence:**

When starting, I refreshed the screen since I had been inactive for a few minutes. Once refreshed, I could see all of my proposals.
Validation messages are ok, and work as expected based on previous testing and evidence shared before. 

Only missing discord handle autofill & confirmation message improvement:
https://github.com/MinaFoundation/pgt-web-app/issues/8#issuecomment-2505874994
https://github.com/MinaFoundation/pgt-web-app/issues/8#issuecomment-2507798734

https://github.com/user-attachments/assets/5c9a3ca8-b72e-49a2-b885-5307e851f9cd
