### ISSUE TITLE
Proposal Creation: Review list of proposal drafts

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/pgt-web-app#9]
**User Story:** 
As a community member,
I want to create proposals easily 
so that I can participate in the governance process without needing to leave the platform

**Acceptance Criteria:**
- Given that the user wants to review a proposal draft,
- When the user clicks on My proposal section,
- [x] Then the user will be able to see his drafts

Provisional UI: https://app.visily.ai/projects/4a98eee4-af36-416a-8432-88b586730009/boards/1351944/elements/622268529

**Comment by remigiusz-antczak** [comment]
Everything works correctly here, can view and edit drafts:
<img width="1594" alt="image" src="https://github.com/user-attachments/assets/f7f16688-740d-4e55-8396-8f1ec26d79e4">

**Comment by criptowaco** [comment]
Given that I want to review a proposal draft,
When I click on My proposal section,
Then I am able to see my drafts

![image](https://github.com/user-attachments/assets/a705687e-4c7d-44c1-8d44-5ccb8387396c)

**Comment by CristinaEche** [comment]
@iluxonchik  Working as expected:

![Image](https://github.com/user-attachments/assets/55f54ed2-2319-406a-b760-34407e583292)
